{"uid":"9aa2fb87196ccba7","name":"test_login_unsuccessful_with_invalid_username_2___rohit12_4__latido_co_np____Test_123__","fullName":"TestLogin.TestLogin#test_login_unsuccessful_with_invalid_username_2___rohit12_4__latido_co_np____Test_123__","historyId":"2ce9702f5b31da0042d1d5b42faf88df","time":{"start":1681970489976,"stop":1681970495662,"duration":5686},"status":"failed","statusMessage":"AssertionError: \"2 validation errors detected: Value at '[251 chars]P}]+\" != 'Incorrect username or password.'\n- 2 validation errors detected: Value at 'userAlias' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}]+; Value at 'userName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}]+\n+ Incorrect username or password.\n : Error message verification failed.","statusTrace":"self = <TestsCases.TestLogin.TestLogin testMethod=test_login_unsuccessful_with_invalid_username_2___rohit12_4__latido_co_np____Test_123__>\nusername = 'rohit12#4@ latido.co.np', password = 'Test@123'\n\n    @allure.story(\"Login With Invalid Username\")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data((\"frugal@-latido.com.np\", \"Test@123\"), (\"rohit12#4@ latido.co.np\", \"Test@123\"))\n    @unpack\n    def test_login_unsuccessful_with_invalid_username(self, username, password):\n        self.LoginMethod.nativelogin(self.driver, username, password)\n        try:\n            self.assertEqual(self.Login.verify_login_error_message_for_invalid_email(),\n                             \"Incorrect username or password.\",\n                             msg=\"Error message verification failed.\")\n        # Check if assertion failed\n        except AssertionError as e:\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"TestLoginScreen\",\n                          attachment_type=AttachmentType.PNG)\n            self.log.error(f\"Assertion failed here while finding element. {str(e)}\")\n>           raise e\n\nTestLogin.py:77: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nTestLogin.py:69: in test_login_unsuccessful_with_invalid_username\n    self.assertEqual(self.Login.verify_login_error_message_for_invalid_email(),\nC:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.3\\plugins\\python-ce\\helpers\\pycharm\\teamcity\\diff_tools.py:33: in _patched_equals\n    old(self, first, second, msg)\nE   AssertionError: \"2 validation errors detected: Value at '[251 chars]P}]+\" != 'Incorrect username or password.'\nE   - 2 validation errors detected: Value at 'userAlias' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}]+; Value at 'userName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}]+\nE   + Incorrect username or password.\nE    : Error message verification failed.","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_unittest_setUpClass_fixture_TestLogin","time":{"start":1681970440027,"stop":1681970440027,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0}],"testStage":{"status":"failed","statusMessage":"AssertionError: \"2 validation errors detected: Value at '[251 chars]P}]+\" != 'Incorrect username or password.'\n- 2 validation errors detected: Value at 'userAlias' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}]+; Value at 'userName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}]+\n+ Incorrect username or password.\n : Error message verification failed.","statusTrace":"self = <TestsCases.TestLogin.TestLogin testMethod=test_login_unsuccessful_with_invalid_username_2___rohit12_4__latido_co_np____Test_123__>\nusername = 'rohit12#4@ latido.co.np', password = 'Test@123'\n\n    @allure.story(\"Login With Invalid Username\")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data((\"frugal@-latido.com.np\", \"Test@123\"), (\"rohit12#4@ latido.co.np\", \"Test@123\"))\n    @unpack\n    def test_login_unsuccessful_with_invalid_username(self, username, password):\n        self.LoginMethod.nativelogin(self.driver, username, password)\n        try:\n            self.assertEqual(self.Login.verify_login_error_message_for_invalid_email(),\n                             \"Incorrect username or password.\",\n                             msg=\"Error message verification failed.\")\n        # Check if assertion failed\n        except AssertionError as e:\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"TestLoginScreen\",\n                          attachment_type=AttachmentType.PNG)\n            self.log.error(f\"Assertion failed here while finding element. {str(e)}\")\n>           raise e\n\nTestLogin.py:77: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nTestLogin.py:69: in test_login_unsuccessful_with_invalid_username\n    self.assertEqual(self.Login.verify_login_error_message_for_invalid_email(),\nC:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.3\\plugins\\python-ce\\helpers\\pycharm\\teamcity\\diff_tools.py:33: in _patched_equals\n    old(self, first, second, msg)\nE   AssertionError: \"2 validation errors detected: Value at '[251 chars]P}]+\" != 'Incorrect username or password.'\nE   - 2 validation errors detected: Value at 'userAlias' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}]+; Value at 'userName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}]+\nE   + Incorrect username or password.\nE    : Error message verification failed.","steps":[],"attachments":[{"uid":"78890859fdcd7467","name":"TestLoginScreen","source":"78890859fdcd7467.png","type":"image/png","size":105077},{"uid":"5bbf3f8f7386589f","name":"log","source":"5bbf3f8f7386589f.txt","type":"text/plain","size":534}],"parameters":[],"stepsCount":0,"hasContent":true,"shouldDisplayMessage":true,"attachmentsCount":2},"afterStages":[{"name":"_unittest_setUpClass_fixture_TestLogin::0","time":{"start":1681970525889,"stop":1681970525889,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"hasContent":false,"shouldDisplayMessage":false,"attachmentsCount":0}],"labels":[{"name":"feature","value":"Login Page"},{"name":"story","value":"Login With Invalid Username"},{"name":"severity","value":"normal"},{"name":"suite","value":"TestLogin"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"0day"},{"name":"thread","value":"1872-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"TestLogin"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"9aa2fb87196ccba7.json","parameterValues":[]}